### ISSUE TITLE
What's new

### ISSUE THREAD

**Issue by Artjaazz** [Antondomashnev/nabokov#23]
Hi Anton,
I'm a localizer. An interesting project you have, but I'm not sure how different is it from existing tools like Weblate, Mojito, or Pootle? (you may google those, easy to find)

**Comment by Antondomashnev** [comment]
Hi @Artjaazz thanks for pointing out this interesting question 👍 I'll check them for sure, but main purpose of this project was to learn ruby by example. 
Anyway, I'll get back with an answer soon 🚀

**Comment by Antondomashnev** [comment]
I've checked all of them, and I found that [weblate](https://github.com/nijel/) is really powerful. And is well integrated with the GitHub, which was an idea of nabokov. 
Other services I haven't found really interesting. So as a conclusion I can say that nabokov is a really simple solution that could work for, but, of course, there are much more mature projects.
